{{- if .Values.kyma.api.enabled -}}
{{- if lt (semver .Values.kyma.version | (semver "1.12.0-0").Compare) 0 -}}
{{- $name := include "chart.name" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  {{- include "default_metadata" . | indent 2 }}
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: {{ $name }}
    port: {{ $svcPort }}
    host: {{ $name }}-{{ .Release.Namespace }}
  rules:
    - path: /.*
      methods: ["GET", "POST", "PUT", "DELETE"]
      accessStrategies:
        - handler: noop
          config: {}
{{- end }}
{{- end }}